workflows:
  ios-workflow:
    name: فجلة
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS app
        script: flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      app_store_connect:
        apple_id: "zaidoona081@gmail.com"
        api_key_id: "TJWY33FYXY"
        issuer_id: "31c5c3e7-22bb-499b-8d0f-df7e49582ae1"
